# add if OCR-D Controller is to be managed from here, centrally

services:

  ocrd-controller:
    extends:
      file: _modules/ocrd_controller/docker-compose.yml
      service: ocrd-controller

  ocrd-manager:
    depends_on:
      - ocrd-controller
