version: "3.9"
services:

    ocrd-controller:
        image: bertsky/ocrd_controller:latest
        
        environment:
          - UID=1001
          - GID=1001
          - UMASK=0002
        
        ports:
           - "8022:22"
           - "8085:8085"
           
        volumes:
           - type: bind
             source: ./ocrd/controller/.ssh/authorized_keys
             target: /authorized_keys
           - ./ocrd/share/data:/data # Shared data directory
           - ./ocrd/controller/models/:/models # Resource directory
           - ./ocrd/controller/config/:/config
        
    ocrd-manager:
        image: markusweigelt/ocrd_manager:latest

        environment:
          - UID=1001
          - GID=1001
          - UMASK=0002

        ports:
           - "9022:22"

        volumes:
           - type: bind
             source: ./ocrd/manager/.ssh/authorized_keys
             target: /authorized_keys 
           - type: bind
             source: ./ocrd/manager/.ssh/id_rsa
             target: /id_rsa
           - ./ocrd/share/data:/data # Shared data directory  

        tty: true # docker run -t
        
        
    kitodo-app:
       image: markusweigelt/kitodo-production:3.4.1

       ports:
        - 8080:8080 

       volumes:
        - ./kitodo/config_modules:/usr/local/kitodo

       environment:
        - KITODO_DB_HOST=kitodo-db
        - KITODO_ES_HOST=kitodo-es
        - KITODO_MQ_HOST=kitodo-mq

       depends_on:
        - kitodo-mq
        - kitodo-db
        - kitodo-es
        
        
    kitodo-db:
        image: mysql:8.0.26

        environment:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: kitodo
          MYSQL_USER: kitodo
          MYSQL_PASSWORD: kitodo

        ports:
          - 3306:3306    


    kitodo-es:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1

        environment:
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - cluster.name=kitodo
            - node.name=kitodo-1
            - xpack.security.enabled=false

        ports:
            - 9200:9200
            - 9300:9300    
            
            
    kitodo-mq:
        image: markusweigelt/activemq:latest
        
        ports:
           - 61616:61616
           - 8161:8161
           
        volumes:   
           - type: bind
             source: ./kitodo-activemq.xml
             target: /opt/activemq/conf/activemq.xml