version: "3.9"
services:

    ocrd-controller:
        image: bertsky/ocrd_controller:latest
        
        environment:
          - UID=1001
          - GID=1001
          - UMASK=0002
        
        ports:
           - "8022:22"
           - "8085:8085"
           
        volumes:
           - type: bind
             source: ./ocrd/controller/.ssh/authorized_keys # ocrd manager public key
             target: /authorized_keys
           - ./kitodo/config_modules/metadata:/data # metadata directory  
           - ./ocrd/controller/models/:/models # Resource directory
           - ./ocrd/controller/config/:/config
        
    ocrd-manager:
        image: markusweigelt/ocrd_manager:latest

        environment:
          - UID=1001
          - GID=1001
          - UMASK=0002
          - "CONTROLLER=ocrd-controller:22"
          - "ACTIVEMQ=kitodo-mq:61616"
          
        ports:
           - "9022:22"

        volumes:
           - type: bind
             source: ./ocrd/manager/.ssh/authorized_keys # kitodo public key
             target: /authorized_keys
           - type: bind
             source: ./ocrd/manager/.ssh/id_rsa
             target: /id_rsa
           - ./kitodo/config_modules/metadata:/data # metadata directory  

        tty: true # docker run -t
        