services:

  ocrd-manager:
    extends:
      file: _modules/ocrd_manager/docker-compose.yml
      service: ocrd-manager

  ocrd-monitor:
    extends:
      file: _modules/ocrd_manager/ocrd_monitor/docker-compose.yml
      service: ocrd-monitor

  dozzle:
    extends:
      file: _modules/ocrd_manager/ocrd_monitor/docker-compose.yml
      service: dozzle

# not defined here (to be replaced by docker-compose.managed.yml if needed):
# service ocrd-controller

# not defined here (to be included on command-line):
# services from _modules/kitodo-production-docker/ and their local overrides
# - kitodo-app
# - kitodo-db
# - kitodo-es
# - kitodo-mq
