version: "3.9"
services:

    ocrd-manager:
        build: ./_modules/ocrd_manager/
        
        image: ${MANAGER_IMAGE}:${MANAGER_IMAGE_TAG}

        hostname: ${MANAGER_HOST}

        environment:
          - UID=${MANAGER_ENV_UID}
          - GID=${MANAGER_ENV_GID}
          - UMASK=${MANAGER_ENV_UMASK}
          - "CONTROLLER=${CONTROLLER_HOST}:22"
          - "ACTIVEMQ=kitodo-mq:61616"
          
        ports:
           - ${MANAGER_PORT_SSH}:22

        volumes:
           - type: bind
             source: ./ocrd/manager/.ssh/authorized_keys # kitodo public key
             target: /authorized_keys
           - type: bind
             source: ./ocrd/manager/.ssh/id_rsa
             target: /id_rsa
           - ./kitodo/config_modules/metadata:/data # metadata directory   

        tty: true # docker run -t
        
        depends_on:
            - ocrd-controller # cause of known host generation for ssh
        
    kitodo-app:
       build: ./_modules/kitodo-production-docker/docker-image/

       ports:
        - 8080:8080

       volumes:
        - type: bind
          source: ./kitodo/.ssh/id_rsa
          target: /id_rsa
        - type: bind
          source: ./_resources/kitodo.sql # overwrite default 3.4.1 database
          target: /tmp/kitodo/kitodo.sql
        - ./kitodo/config_modules:/usr/local/kitodo

       environment:
        - KITODO_DB_HOST=kitodo-db
        - KITODO_ES_HOST=kitodo-es
        - KITODO_MQ_HOST=kitodo-mq
        - "OCRD_MANAGER=${MANAGER_HOST}:22"

       depends_on:
        - kitodo-db
        - kitodo-es
        - kitodo-mq
        - ocrd-manager # cause of known host generation for ssh
        
    kitodo-db:
        image: mysql:8.0.26

        environment:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: kitodo
          MYSQL_USER: kitodo
          MYSQL_PASSWORD: kitodo

        ports:
          - 3306:3306    


    kitodo-es:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2

        environment:
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - cluster.name=kitodo
            - node.name=kitodo-1
            - xpack.security.enabled=false

        ports:
            - 9200:9200
            - 9300:9300    
            
            
    kitodo-mq:
        image: markusweigelt/activemq:latest
        
        ports:
           - 61616:61616
           - 8161:8161
           
        volumes:   
           - type: bind
             source: ./_resources/kitodo-activemq.xml
             target: /opt/activemq/conf/activemq.xml