version: "3.9"
services:

    ocrd-controller:
        build: ./_modules/ocrd_controller/
        
        image: ${CONTROLLER_IMAGE}:${CONTROLLER_IMAGE_TAG}
        
        hostname: ${CONTROLLER_HOST}
        
        environment:
          - UID=${CONTROLLER_ENV_UID}
          - GID=${CONTROLLER_ENV_GID}
          - UMASK=${CONTROLLER_ENV_UMASK}
        
        ports:
           - ${CONTROLLER_PORT_SSH}:22
           
        volumes:
           - type: bind
             source: ./ocrd/controller/.ssh/authorized_keys # ocrd manager public key
             target: /authorized_keys
           - ./kitodo/config_modules/metadata:/data # metadata directory  
           - ./ocrd/controller/models/:/models # Resource directory
           - ./ocrd/controller/config/:/config
        