version: "3.9"
services:

  ocrd-manager:
    build: 
      context: _modules/ocrd_manager
      dockerfile: Dockerfile
    
    image: ${MANAGER_IMAGE}:${MANAGER_IMAGE_TAG}

    hostname: ${MANAGER_HOST}

    environment:
      - UID=${MANAGER_ENV_UID}
      - GID=${MANAGER_ENV_GID}
      - UMASK=${MANAGER_ENV_UMASK}
      - "CONTROLLER=${CONTROLLER_HOST}:22"
      - "ACTIVEMQ=kitodo-mq:61616"
      
    ports:
        - ${MANAGER_PORT_SSH}:22

    depends_on:
      - ocrd-controller

    volumes:
        - type: bind
          source: ./ocrd/manager/.ssh/authorized_keys # kitodo public key
          target: /authorized_keys
        - type: bind
          source: ./ocrd/manager/.ssh/id_rsa
          target: /id_rsa
        - ./kitodo/config_modules/metadata:/data # metadata directory   

    tty: true # docker run -t
    