site_name: Kitodo.Production using OCR-D

repo_url: https://github.com/slub/ocrd_kitodo

nav:
  - Home: 'index.md'
  - 'Getting started': 'getting-started.md'
  - Setup:
    - Prerequisites: 'setup/prerequisites.md'
    - Configuration:
      - Compose Profiles: 'setup/compose-profiles.md'
      - Modules:
        - 'OCR-D Manager and Monitor': 'setup/modules/ocrd-manager-and-monitor.md'
        - 'OCR-D Controller': 'setup/modules/ocrd-controller.md'
        - 'Kitodo.Production': 'setup/modules/kitodo-production.md'
    - Preparation: 'setup/preparation.md'
    - Handling: 'setup/handling.md'
  - Usage:
    - Kitodo.Production: 'usage/kitodo-production.md'
    - OCR-D Monitor: 'usage/ocrd-monitor.md'

plugins:
  - monorepo
  - search
  - exclude-search:
      exclude:
        - _generated/*
  - macros

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - toc.follow
  palette:
    primary: blue grey
    accent: light blue
