site_name: Kitodo.Production using OCR-D

repo_url: https://github.com/slub/ocrd_kitodo

nav:
  - Home: 'index.md'
  - 'Getting started': 'getting-started.md'
  - Setup:
    - Prerequisites: 'setup/prerequisites.md'
    - Enable/Disable Modules: 'setup/enable-disable-modules.md'
    - Configure Modules: 'setup/configure-modules.md'
    - Preparation: 'setup/preparation.md'
    - Running: 'setup/running.md'
  - Usage:
    - Demo: 'usage/demo.md'
    - 'Kitodo.Production': 'usage/kitodo-production.md'
    - 'OCR-D Monitor': 'usage/ocrd-monitor.md'

plugins:
  - monorepo
  - search
  - exclude-search:
      exclude:
        - _generated/*
        - _includes/*
  - macros

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - toc.follow
  palette:
    primary: blue grey
    accent: light blue
