site_name: Kitodo.Production using OCR-D

repo_url: https://github.com/slub/ocrd_kitodo

nav:
  - Home: 'index.md'
  - 'Getting started': 'getting-started.md'
  - Setup:
    - Prerequisites: 'setup/prerequisites.md'
    - Configuration: 'setup/configuration.md'
    - Preparation: 'setup/preparation.md'
    - Handling: 'setup/handling.md'
  - Modules:
      - 'OCR-D Manager': 'modules/ocrd-manager.md'
      - 'OCR-D Monitor': 'modules/ocrd-monitor.md'
      - 'OCR-D Controller': 'modules/ocrd-controller.md'
      - 'Kitodo.Production': 'modules/kitodo-production.md'
  - Demo: 'demo.md'

plugins:
  - monorepo
  - search
  - exclude-search:
      exclude:
        - _generated/*
  - macros

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - toc.follow
  palette:
    primary: blue grey
    accent: light blue
