name: Publish Kitodo.Production for OCR-D

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
     
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build the OCR-D Kitodo.Production image and deploy to GitHub Container Repository
        run: |
          DOCKER_BUILDKIT=1 docker build ./_modules/kitodo-production-docker/kitodo --tag ghcr.io/markusweigelt/kitodo-production-ocrd:latest --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") --build-arg VCS_REF=$(git rev-parse --short HEAD) --build-arg BUILDER_TYPE="git" --build-arg BUILDER_GIT_COMMIT="ocrd-main" --build-arg BUILDER_GIT_SOURCE_URL="https://github.com/markusweigelt/kitodo-production/"
          docker push ghcr.io/markusweigelt/kitodo-production-ocrd:latest
