name: Makefile CI

on:
  # Triggers the workflow on push and pull request events but only for pull_requests on the main branch
  push:
    branches:
      - main
      - stable
  
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually
  workflow_dispatch:

jobs:
  build:
    environment: OCRD_KITODO
    runs-on: ubuntu-latest

    steps:
    - name: Install nvidia-container-runtime
      run: |
        curl -s -L https://nvidia.github.io/nvidia-container-runtime/gpgkey | sudo apt-key add -
        distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
        curl -s -L https://nvidia.github.io/nvidia-container-runtime/$distribution/nvidia-container-runtime.list | sudo tee /etc/apt/sources.list.d/nvidia-container-runtime.list
        sudo apt-get update
        sudo apt-get install -y nvidia-container-toolkit
        sudo systemctl restart docker
    
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
     #- name: Prepare
     #  run: make prepare 
    
    # - name: Build images from submodules
    #   run: make build

    # - name: Start 
    #   run: make start
    
    # - name: Test
    #   run: make test 
      
    #- name: Clean testdata
    #  run: make clean-testdata

    #- name: Test parallel using multiple workers 
    #  run: CONTROLLER_WORKERS=3 make -j test 
    
    # - name: Clean
     #  run: |
     #    make down
      #   make clean
      #   docker system prune -a
    
    - name: Dispatch OCR-D Controller workflow and waiting for completion
      uses: aurelien-baudet/workflow-dispatch@v2
      with:
        ref: 'master'
        repo: ${{ context.repo.owner }}/ocrd_controller
        token: ${{ secrets.SUB_REPO_TOKEN }}
        workflow: publish.yml
    
    - name: Dispatch OCR-D Manager workflow and waiting for completion
      uses: aurelien-baudet/workflow-dispatch@v2
      with:
        ref: 'main'
        repo: ${{ context.repo.owner }}/ocrd_manager
        token: ${{ secrets.SUB_REPO_TOKEN }}
        workflow: publish.yml
    
    - name: Dispatch OCR-D Monitor workflow and waiting for completion
      uses: aurelien-baudet/workflow-dispatch@v2
      with:
        ref: 'main'
        repo: ${{ context.repo.owner }}/ocrd_monitor
        token: ${{ secrets.SUB_REPO_TOKEN }}
        workflow: publish.yml

    - name: Prepare
      run: make prepare 
  
    - name: Start 
      run: make start
    
    - name: Test
      run: make test 
      
    - name: Clean testdata
      run: make clean-testdata

    - name: Test parallel using multiple workers 
      run: CONTROLLER_WORKERS=3 make -j test 
