name: Makefile CI

on:
  # Triggers the workflow on push and pull request events but only for pull_requests on the main branch
  push:
    branches:
      - main
      - stable
  
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually
  workflow_dispatch:

env:
  IMAGE_TAG: latest
  OCRD_ALL_VERSION: maximum-git

jobs:
  build:
    environment: OCRD_KITODO
    runs-on: ubuntu-latest

    steps:
    - name: Set environment variables for the stable version
      if: endsWith(github.ref, '/stable')
      run: |
        echo "IMAGE_TAG=stable" >> $GITHUB_ENV
        echo "OCRD_ALL_VERSION=2023-02-07" >> $GITHUB_ENV
        
    - name: Install nvidia-container-runtime
      run: |
        curl -s -L https://nvidia.github.io/nvidia-container-runtime/gpgkey | sudo apt-key add -
        distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
        curl -s -L https://nvidia.github.io/nvidia-container-runtime/$distribution/nvidia-container-runtime.list | sudo tee /etc/apt/sources.list.d/nvidia-container-runtime.list
        sudo apt-get update
        sudo apt-get install -y nvidia-container-toolkit
        sudo systemctl restart docker
    
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
     
    - # Activate cache export feature to reduce build time of images
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

     #- name: Prepare
     #  run: make prepare 
    
    # - name: Build images from submodules
    #   run: make build

    # - name: Start 
    #   run: make start
    
    # - name: Test
    #   run: make test 
      
    #- name: Clean testdata
    #  run: make clean-testdata

    #- name: Test parallel using multiple workers 
    #  run: CONTROLLER_WORKERS=3 make -j test 
    
    # - name: Clean
     #  run: |
     #    make down
      #   make clean
      #   docker system prune -a
    
    - name: Determine submodule Git references
      run: |
        echo "CHECKOUT_REF_OCRD_CONTROLLER=`git -C ./_modules/ocrd_controller rev-parse HEAD`" >> $GITHUB_ENV
        echo "CHECKOUT_REF_OCRD_MANAGER=`git -C ./_modules/ocrd_manager rev-parse HEAD`" >> $GITHUB_ENV
        echo "CHECKOUT_REF_OCRD_MONITOR=`git -C ./_modules/ocrd_monitor rev-parse HEAD`" >> $GITHUB_ENV
    
    - name: Dispatch OCR-D Controller workflow and waiting for completion
      uses: aurelien-baudet/workflow-dispatch@v2
      with:
        inputs: '{ "checkout-ref": "${{ env.CHECKOUT_REF_OCRD_CONTROLLER }}", "image-tag": "${{ env.IMAGE_TAG }}", "ocrd-all-version": "${{ env.OCRD_ALL_VERSION }}" }'
        ref: 'master'
        repo: slub/ocrd_controller
        token: ${{ secrets.SUB_REPO_TOKEN }}
        workflow: publish.yml
    
    - name: Dispatch OCR-D Manager workflow and waiting for completion
      uses: aurelien-baudet/workflow-dispatch@v2
      with:
        inputs: '{ "image-tag": "${{ env.IMAGE_TAG }}" }'
        ref: '${{ env.git_ref_ocrd_manager }}'
        repo: slub/ocrd_manager
        token: ${{ secrets.SUB_REPO_TOKEN }}
        workflow: publish.yml
    
    - name: Dispatch OCR-D Monitor workflow and waiting for completion
      uses: aurelien-baudet/workflow-dispatch@v2
      with:
        inputs: '{ "image-tag": "${{ env.IMAGE_TAG }}" }'
        ref: '${{ env.git_ref_ocrd_monitor }}'
        repo: slub/ocrd_monitor
        token: ${{ secrets.SUB_REPO_TOKEN }}
        workflow: publish.yml

    #- name: Prepare
     # run: make prepare 
  
    #- name: Start 
    #  run: make start
    
   # - name: Test
    #  run: make test 
      
   # - name: Clean testdata
   #   run: make clean-testdata

   # - name: Test parallel using multiple workers 
   #   run: CONTROLLER_WORKERS=3 make -j test 
