name: Publish Kitodo.Production for OCR-D

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY_PATH: ghcr.io/markusweigelt/kitodo-production-ocrd

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - # Activate cache export feature to reduce build time of images
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
     
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build the OCR-D Controller image from module and deploy to GitHub Container Repository
        uses: docker/build-push-action@v3
        env: 
          IMAGE: ${{ env.REGISTRY_PATH }}/ocrd_controller:latest
        with:
          context: ./_modules/ocrd_controller
          push: true
          tags: ${{IMAGE}}
          build-args: |
            BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            VCS_REF=$(git rev-parse --short HEAD)
          cache-from: type=registry,ref=${{IMAGE}}
          cache-to: type=registry,ref=${{IMAGE}},mode=max
      
      - name: Build the OCR-D Manager image from module and deploy to GitHub Container Repository
        uses: docker/build-push-action@v3
        with:
          context: ./_modules/ocrd_manager
          push: true
          tags: ${{ env.REGISTRY_PATH }}/ocrd_manager:latest
          build-args: |
            BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            VCS_REF=$(git rev-parse --short HEAD)
          cache-from: type=registry,ref=${{ env.REGISTRY_PATH }}/ocrd_manager:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY_PATH }}/ocrd_manager:buildcache,mode=max
          
      - name: Build the OCR-D Monitor image from module and deploy to GitHub Container Repository
        uses: docker/build-push-action@v3
        with:
          context: ./_modules/ocrd_manager/ocrd_monitor
          push: true
          tags: ${{ env.REGISTRY_PATH }}/ocrd_monitor:latest
          build-args: |
            BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            VCS_REF=$(git rev-parse --short HEAD)
          cache-from: type=registry,ref=${{ env.REGISTRY_PATH }}/ocrd_monitor:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY_PATH }}/ocrd_monitor:buildcache,mode=max
      
      - name: Build the OCR-D Kitodo.Production image from module and deploy to GitHub Container Repository
        uses: docker/build-push-action@v3
        with:
          context: ./_modules/kitodo-production-docker/kitodo
          push: true
          tags: ${{ env.REGISTRY_PATH }}/kitodo-production:latest
          build-args: |
            BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            VCS_REF=$(git rev-parse --short HEAD)
            BUILDER_TYPE=git
            BUILDER_GIT_COMMIT=ocrd-main
            BUILDER_GIT_SOURCE_URL=https://github.com/markusweigelt/kitodo-production/
          cache-from: type=registry,ref=${{ env.REGISTRY_PATH }}/kitodo-production:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY_PATH }}/kitodo-production:buildcache,mode=max
          
