name: Publish Kitodo.Production for OCR-D

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY_PATH: ghcr.io/slub/ocrd_kitodo

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - # Activate cache export feature to reduce build time of images
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
     
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Determine build args
        run: |
          date -u +"build_date=%Y-%m-%dT%H:%M:%SZ" >> $GITHUB_ENV
          echo "vcs_ref=`git -C ./_modules/kitodo-production-docker rev-parse --short HEAD`" >> $GITHUB_ENV
      
      - name: Build the OCR-D Kitodo.Production image from module and deploy to GitHub Container Repository
        uses: docker/build-push-action@v3
        with:
          context: ./_modules/kitodo-production-docker
          push: true
          tags: ${{ env.REGISTRY_PATH }}/kitodo_production_ocrd:latest
          build-args: |
            BUILD_DATE=${{ env.build_date }}
            VCS_REF=${{ env.vcs_ref }}
            BUILDER_TYPE=git
            BUILDER_GIT_COMMIT=ocrd-main
            BUILDER_GIT_SOURCE_URL=https://github.com/markusweigelt/kitodo-production/
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
